config/routes.rb
CupOfSugr::Application.routes.draw do

  resources :categories
  match '/owner_dashboard', to: 'users#owner_dashboard', via: 'get', :as => :owner_dashboard
  match '/my-stars', to: 'users#my-stars', via: 'get',:as => :my_stars
  devise_for :users
  resources :restaurants do
    resources :reservations
    resources :stars, :only => ['new', 'create']
    put :star, on: :member
  end
  resources :reservations
  #root to: "restaurants#index"
  root :to => 'root#root'

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :restaurant
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :restaurants
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	validates_presence_of :email, :message, :reserve_time, :reserve_date
	#before_action :authenticate_user!

	belongs_to :user
	belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    validates_presence_of :name, :description, :phone, :address, :city, :state
    acts_as_gmappable
    belongs_to :user
    has_many :reservations
    has_and_belongs_to_many :categories
    has_many :stars
    has_many :starred_by, through: :stars, source: :user
    mount_uploader :image, ImageUploader

    validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }
    validates_format_of :name, :with => /\A[a-zA-Z0-9 \-']+\Z/,
    :message => "can only contain letters and numbers.", :maximum => '30'
    
    def gmaps4rails_address
        "#{address}, #{city}, #{state}"
    end
end

app/models/star.rb
class Star < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants
  has_many :reservations
  has_many :stars
  has_many :starred_restaurants, :through => :stars, :source => :restaurant

  validates :password, format: { with: /\A(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z]{8,}\z/, message: "must have one capital and one number." }

  def owner?
  	isOwner = false
  	if self.role == "owner"
  		isOwner = true
  	end
  end

  def self.patron?
  	isPatron = false
  	if self.role == "patron"
  		isPatron = true
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end

  def create
  end

  def index
    @categories = Category.all 
  end

  def show
    @category = Category.find(params[:id])
    @restaurants = Restaurant.where(:categories => {:id => params[:id]}).includes(:categories).all
  end

  def destroy
  end

  def update
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    restaurant = Restaurant.all
    @reservations = restaurant
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
  end

  def show
    @reservation = Reservation.find_by_id params[:id]
    if @reservation
      render :show
    else
      flash[:warning] = "sorry that reservation doesn't exist"
      redirect_to root_path
    end
  end

  def create
    @reservation = Reservation.new(reservation_params)

    @restaurant = Restaurant.find_by_id(@reservation.restaurant_id)
    if @reservation.save
      ReservationMailer.confirm_email(@restaurant.user).deliver
      flash[:success] = "#{@reservation.id} created"
      redirect_to @reservation
    else
      flash[:warning] = @reservation.errors.inspect
      redirect_to new_reservation_path
    end
  end

  def new
    @reservation = Reservation.new
    @restaurant = Restaurant.find_by_id params[:restaurant_id]
  end

  def update
  end

  def edit
  end

  def destroy
    @reservation = Reservation.find_by_id params[:id]
    @reservation.destroy
    redirect_to root_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:email, :message, :reserve_time, :reserve_date, :restaurant_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :find_restaurant, :only => [:show, :edit, :update, :destroy]  

  def show
    @current_reservations = Reservation.find_all_by_restaurant_id(@restaurant.id)
    cookies[:name] = @restaurant.name
    @json = Restaurant.find(params[:id]).to_gmaps4rails
    Rails.logger.info("Json: #{@json.inspect}")
    if current_user
     @starred = current_user.stars.exists?(:restaurant_id => @restaurant.id)
   end
   if @restaurant
    render :show
  else
    flash[:warning] = "sorry that restaurant doesn't exist"
    redirect_to root_path
  end
end

def index
 @restaurants = Restaurant.all
 @categories = Category.all
end

def new
  @restaurant = Restaurant.new
end

def create
  @restaurant = Restaurant.new(restaurant_params)
  @restaurant.user_id = current_user.id

  if @restaurant.save
    current_user.role = "owner"
    flash[:success] = "#{@restaurant.name} created"
    redirect_to @restaurant
  else
    flash[:warning] = @restaurant.errors.inspect
    redirect_to new_restaurant_path
  end
end

def edit
  if @restaurant
    render :edit
  else
    redirect_to root_path
  end
end

def update
  if @restaurant
    @restaurant.update_attributes(name: params[:restaurant][:name])
    flash[:success] = "Name Updated!"
    redirect_to restaurant_path @restaurant
  else
    flash[:alert] = "Houston, we have a problem"
    redirect_to root_path
  end
end

def destroy
  @restaurant = Restaurant.find_by_id params[:id]
  @restaurant.destroy
  redirect_to root_path
end

def star
  type = params[:type]
  @restaurant = Restaurant.find(params[:id])
  if type == "star" 
    current_user.starred_restaurants << @restaurant
    redirect_to :back, notice: 'You starred ' + @restaurant.name
  elsif type == "unstar"
    current_user.starred_restaurants.delete(@restaurant.id)
    redirect_to :back, notice: 'You unstarred ' + @restaurant.name
  else
    redirect_to :back, notice: 'Nothing happened.'
  end
end

private
def restaurant_params
  params.require(:restaurant).permit(:name, :address, :phone, :description, :city, :state, :image, :category_ids => [])
end

protected    
def find_restaurant
  @restaurant = Restaurant.find_by_id params[:id]
end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def root
    render :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	def dashboard
		@restaurant = Restaurant.find_all_by_user_id(current_user.id)
	end

	def owner_dashboard
		@user = current_user
		@restaurants = current_user.restaurants
	end

	def my_stars
		@user = current_user
		@all_stars = @user.restaurants.starred_restaurants
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
 
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)
 
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML
 
    html.html_safe
  end
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<div class="container">
	<div class="row text-center">
		<h2 id="details">Categories</h2>
	</div><br>

	<div class="col-md-3 col-center-block">
		<ul class="list-group">
			<% Category.all.each do |category| %>
			<li class="list-group-item"><i class="fa fa fa-cutlery fa-lg">  </i>    &nbsp;<u><%= link_to category.name, category_path(category) %></u></li>
			<% end %>
		</ul>
	</div> 
</div>  
<style>
.col-center-block {
    float: none;
    display: block;
    margin-left: auto;
    margin-right: auto;
}
</style>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<h2> There's 
  <%= pluralize(@restaurants.count, 'restaurant') %> in the <%= @category.name %> category. 
</h2>

<p>
  <% @restaurants.each do |restaurant| %>
  <%= link_to restaurant.name, restaurant_path(restaurant) %>
  <br/> 
  <% end %>
</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Resrvstr</title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

</head>

<body>
  <%= render "root/header" %>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>


  <%= yield %>
  <%= yield :scripts %>
</body>
</html>

app/views/reservations/_form.html.erb
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <!-- Form Name -->
      <legend>Reservation form</legend>

      <%= form_for(reservation, multipart: true, :html => {class: 'form-horizontal'}) do |f| %>
      <!-- Text input-->
      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Email</label>
        <div class="col-sm-10">
          <%= f.text_field :email, :placeholder => "Email", :class => 'form-control' %>
        </div>
      </div>

      <!-- Text input-->
      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Message</label>
        <div class="col-sm-10">
          <%= f.text_area :message, :placeholder => "Message", :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Date</label>
        <div class="col-sm-10">
          <%= f.date_select :reserve_date, :placeholder => "Date", :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Time</label>
        <div class="col-sm-10">
          <%= f.time_select :reserve_time, :ampm => true, :minute_step => 15, :class => 'form-control' %>
        </div>
      </div>


      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="pull-right">
            <%= link_to "Cancel", :back, class: 'btn btn-default' %>
            <%= f.hidden_field :restaurant_id, :value => @restaurant.id %>
            <%= f.submit class: 'btn btn-primary' %>

          </div>
        </div>
      </div>

      <% end %>
    </div><!-- /.col-lg-12 -->
</div><!-- /.row -->

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/new.html.erb
<%= render 'form' %>

app/views/reservations/show.html.erb
<h1>Reservations</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <br><br>

     <h2>Email:</h2> <%= @reservation.email %> <br>
     <h2>Message:</h2> <%= @reservation.message %><br>
     <h2>Reserve Time</h2> <%= @reservation.reserve_time %><br>
     <h2>Reserve Date</h2> <%= @reservation.reserve_date %>

     <h2><%= link_to 'Home', root_path %>
     </h2>
   </div>
 </div>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/restaurants/create.html.haml
%h1 Restaurants#create
%p Find me in app/views/restaurants/create.html.haml

app/views/restaurants/destroy.html.haml
%h1 Restaurants#destroy
%p Find me in app/views/restaurants/destroy.html.haml

app/views/restaurants/edit.html.erb
        <div class="row">
    <div class="col-md-4 col-md-offset-4">

            <legend>Edit Restaurant</legend>
      <!-- Form Name -->
       <%= form_for @restaurant, :html => {class: 'form-horizontal'} do |f| %>

    <!-- Text input-->
      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Name</label>
        <div class="col-sm-10">
          <%= f.text_field :name, :placeholder => "Restaurant name", :class => 'form-control' %>
        </div>
      </div>

      <!-- Text input-->
      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Description</label>
        <div class="col-sm-10">
          <%= f.text_area :description, :placeholder => "Short description", :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Phone</label>
        <div class="col-sm-10">
          <%= f.text_field :phone, :placeholder => "Phone number", :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Address</label>
        <div class="col-sm-10">
          <%= f.text_area :address, :placeholder => "Street address", :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="pull-right">
            <%= link_to "Cancel", :back, class: 'btn btn-default' %>
            <%= f.submit "Update", class: 'btn btn-primary' %>
            
          </div>
        </div>
      </div>

      <% end %>
    </div><!-- /.col-lg-12 -->
</div><!-- /.row -->

app/views/restaurants/edit.html.haml
%h1 Restaurants#edit
%p Find me in app/views/restaurants/edit.html.haml

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
      <% if user_signed_in? %>
      <h3><%= link_to 'Add new restaurant', new_restaurant_path, :class => 'btn btn-warning btn-large' %></h3>
      <% end %>
      <% if !@restaurants.nil? %>
      <% @restaurants.each do |res| %>
      <div class="well">
        <div class="media">

            <%= link_to image_tag(res.image_url(:small_avatar), :width => 100, :height => 100), res, :class => 'pull-left' %>

          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to res.name, res %></h4>
              <p class="text-right"><%= res.address %></p>
              <p>Description: <%= res.description %></p>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/restaurants/new.html.erb
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <!-- Form Name -->
      <h2>Add a new restaurant</h2>

      <%= form_for(@restaurant, multipart: true, :html => {class: 'form-horizontal'}) do |f| %>
      <br>
      <% if @restaurant.errors.any? %>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
      <% end %>

      <!-- Text input-->
      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Name</label>
        <div class="col-sm-10">
          <%= f.text_field :name, :placeholder => "Restaurant name", :class => 'form-control' %>
        </div>
      </div>

      <!-- Text input-->
      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Description</label>
        <div class="col-sm-10">
          <%= f.text_area :description, :placeholder => "Short description", :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Phone</label>
        <div class="col-sm-10">
          <%= f.text_field :phone, :placeholder => "XXX-XXX-XXXX", :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Address</label>
        <div class="col-sm-10">
          <%= f.text_field :address, :placeholder => "Street Address", :class => 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">City</label>
        <div class="col-sm-4">
          <%= f.text_field :city, :placeholder => "City Name", :class => 'form-control' %>
        </div>
        <label class="col-sm-2 control-label" for="textinput">State</label>
        <div class="col-sm-4">
          <%= f.text_field :state, :placeholder => "State", :class => 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="textinput">Upload Photo</label>
        <div class="col-sm-10">
          <%= f.file_field :image %>
        </div>
      </div>

      <h3>Categories</h3>
      <% Category.all.each do |category| %>
      <%= check_box_tag "restaurant[category_ids][]", category.id, @restaurant.categories.include?(category) %>
      <%= category.name %><br/>
      <% end %>
      <br>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="pull-right">
            <%= link_to "Cancel", :back, class: 'btn btn-default' %>
            <%= f.submit class: 'btn btn-primary' %>

          </div>
        </div>
      </div>

      <% end %>
    </div><!-- /.col-lg-12 -->
</div><!-- /.row -->

app/views/restaurants/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="container">

  <!-- Portfolio Item Heading -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><%= @restaurant.name %>
        <small><%= @restaurant.address %>, <%= @restaurant.city %>, <%= @restaurant.state %></small>
        <br>
      </h1>
    </div>
  </div>
  <!-- /.row -->

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-8" style="padding-bottom: 70px">
      <% if @restaurant.image_url.nil? %>
      <%= image_tag @restaurant.image_url(:thumb), :class => 'img-responsive' %>
      <% else %>
      <%= image_tag "/assets/notavail.png", :class => 'img-responsive', :width => 700, :height => 400 %>
      <% end %>
    </div>

    <div class="col-md-4">
      <h3>Description</h3>
      <p><%= @restaurant.description %></p>
      <% if current_user %>
      <% if @starred %>
      <%= link_to "Unstar", star_restaurant_path(@restaurant, type: "unstar"), method: :put, :class => 'btn btn-warning fa fa-star-o' %>
      <% else %>
      <%= link_to "Star", star_restaurant_path(@restaurant, type: "star"), method: :put, :class => 'btn btn-warning fa fa-star' %>
      <% end %>
      <% end %>
      <h4>Contact:</h4> <%= @restaurant.phone %>
    </div>

        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                  <center>
      <%= gmaps({ 'map_options' => {'auto_zoom' => false, 'zoom' => 17 }, 'markers' => {'data' => @json }}) %></center>
      <br><br>
    </div>
  </div>
  </div>

      <%= render partial: 'reservations/form', :locals => { reservation: Reservation.new(restaurant_id: @restaurant.id) } %>
      <% if current_user.owner? %>

      <h2><%= link_to 'Edit', edit_restaurant_path %>
       <%= link_to 'Delete', @restaurant , method: :delete %></h2>

       <% @current_reservations.each do |reserve| %>
       <div class="row">
        <div class="col-md-4 col-md-offset-4">
         <h2><%= reserve.email %></h2>
         <%= link_to 'Destroy', { :controller => "reservations", :action => 'destroy', :id => reserve.id}, method: :delete %>

       </div>
     </div>
     <% end %>

     <% end %>

   </div>
   <!-- /.row -->

 </div>

app/views/restaurants/update.html.haml
%h1 Restaurants#update
%p Find me in app/views/restaurants/update.html.haml

app/views/root/_header.html.erb
 <!-- Navigation -->
 <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <center><%= link_to "Cup Of Sugr", root_path, :class => 'navbar-brand page-scroll' %></center>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <% if user_signed_in? %>
                                <li>
                    <%= link_to "Restaurants", restaurants_path, :class => 'page-scroll' %>
                </li>
                <li><%= link_to "Categories", categories_path, :class => 'page-scroll' %></li>
                <li>
                    <%= link_to "Your Restaurants", owner_dashboard_path, :class => 'page-scroll' %>
                </li>
                <li>
                   <%= link_to "My Favorites", my_stars_path, :class => 'page-scroll' %>
               </li>
               <li>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'page-scroll' %>
            </li>
            <li>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'page-scroll' %>
            </li>

            <% else %>
            <!--
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'page-scroll'  %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'page-scroll'  %></li>
            -->
            <% end %>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>

app/views/users/my-stars.html.erb
    <div class="container">
    	<div class="row">
    		<br>
    		<% if @all_stars %>
    		<% @all_stars.each do |x| %>
    		<%= debug x %>
    		<% end %>
    		<% else %>
    		You don't have any current starred restaurants!
    		<% end %>
    	</div>
    </div>

app/views/users/owner_dashboard.html.erb
    <div class="container">
    	<div class="row">
    		<div class="[ col-xs-12 col-sm-offset-2 col-sm-6 ]">
                <br>
                <br>
                <% if !@restaurants.empty? %>

                <% @restaurants.each do |res| %>
                <div class="well">
                    <div class="media">
                     <%= link_to image_tag(res.image_url(:small_avatar), :width => 100, :height => 100), res, :class => 'pull-left' %>
                     <div class="media-body">
                      <h4 class="media-heading">
                         <%= link_to res.name, res %></h4>
                         <p>Description: <%= res.description %></p>
                         <p class="text-right">Stars: <%= res.stars.count %></p>
                     </div>
                 </div>
             </div>
             <% end %>

             <% else %>
             You don't have any restaurants yet!
             <% end %>

             <h3><%= link_to 'Add new restaurant', new_restaurant_path, :class => 'btn btn-warning btn-large' %></h3>

         </div>
     </div>
 </div>